### ISSUE TITLE
Move to organization

### ISSUE THREAD

**Issue by HereAround** [oscar-system/JToric#28]
@fingolfin @lkastner: For efficient collaboration, I think you should have sufficient permissions (write, merge etc.). Does it make sense to migrate this repository to Oscar?

I have done similar transitions in the past. It should be possible to hand over this private repository to an organization (e.g. Oscar). In particular, this transition should (?) also preserve issues, PRs etc.

**Comment by fingolfin** [comment]
Sure! I've sent you an invite to oscar-system (and to our Slack). Once you accept that, you can (I think) initiate the transfer.
